version: '3.9'

networks:
  dev-network:
    driver: bridge

services:

  app:
    build: ./docker/php
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - dev-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "${NGINX_PORT}:80"
    networks:
      - dev-network

  redis:
    build: ./docker/redis
    container_name: redis
    tty: true
    volumes:
    - ./docker/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - dev-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    tty: true
    volumes:
      - ./docker/mariadb/data:/var/lib/mysql/
      - ./docker/mariadb/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - dev-network

  laravel-echo-server:
    build: ./docker/echo-server
    container_name: laravel-echo-server
    volumes:
      - ./docker/echo-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
    ports:
      - "${WEBSOCKET_PORT}:6001"
    links:
      - redis
    networks:
      - dev-network
